---
name: Check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch full history for version tags
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'


      - name: Run format check
        run: make formatcheck

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Build
        run: make build
